apiVersion: v1
kind: Pod
metadata:
  name: simpleapp-liveness-pod
spec:
  initContainers:
  - name: init-ctr
    image: busybox:1.28.4
    command: ['sh', '-c', 'until nslookup appsvc; do echo waiting for appsvc service;\
              sleep 1; done; echo Service found!']
  containers:
    - name: simpleapp-container
      image: carlosquintanilha/simpleapp:v0.1
      ports:
      - containerPort: 8000
      imagePullPolicy: Always
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
