apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: simpleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp-container
        image: carlosquintanilha/simpleapp:v0.1
        ports:
        - containerPort: 8000
        