apiVersion: v1
kind: Pod
metadata:
  name: simpleapp-pod
spec:
  containers:
    - name: simpleapp-container
      image: carlosquintanilha/simpleapp:v0.1
      ports:
      - containerPort: 8000
      imagePullPolicy: Always
      